spring:
  cloud:
    bus:
      enabled: true
    config:
      server:
        git:
          uri: ${GIT_URI}
          search-paths: '{application}'
          refresh-rate: 60
  rabbitmq:
    host: rabbit
